joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.1
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1  # See joy_layout for value -- current = Up/Down Axis stick left
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 3  # See joy_layout for value -- current = Left/Rigth Axis stick right
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 1.2

    
    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true
