<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="link_macros.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="materials.xacro" />
    <xacro:include filename="gazebo_tags.xacro" />

    <xacro:property name="chassis_length" value="0.2"/>
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.08"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.115"/>
    <xacro:property name="wheel_offset_y" value="0.0"/>
    <xacro:property name="wheel_offset_z" value="0.012"/>
    <xacro:property name="caster_wheel_radius" value="0.0125"/> <!-- 0.0205 if offset_z = 0-->
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.06"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <!-- BASE LINK -->

    <link name="base_link">
    </link>


    <!-- BASE_FOOTPRINT LINK -->
    <!-- use for slam -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="light_grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- LEFT WHEEL -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_x} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <xacro:wheel_link wheel_name="left_wheel" />


    <!-- RIGHT WHEEL -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_x} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <xacro:wheel_link wheel_name="right_wheel" />


    <!-- FRONT CASTER WHEEL -->

    <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="front_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <!-- BACK CASTER WHEEL -->

    <joint name="back_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="back_caster_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="back_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    
</robot>