joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.1
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1  
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 2  
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 1.2

    
    enable_button: 5
    enable_turbo_button: 2

    require_enable_button: true
